#███████╗███╗░░░███╗███╗░░██╗░█████╗░████████╗██╗███████╗██╗░░░██╗░█████╗░███████╗██████╗░░█████╗░██╗██████╗░
#██╔════╝████╗░████║████╗░██║██╔══██╗╚══██╔══╝██║██╔════╝╚██╗░██╔╝██╔══██╗██╔════╝██╔══██╗██╔══██╗██║██╔══██╗
#█████╗░░██╔████╔██║██╔██╗██║██║░░██║░░░██║░░░██║█████╗░░░╚████╔╝░██║░░██║█████╗░░██████╔╝███████║██║██║░░██║
#██╔══╝░░██║╚██╔╝██║██║╚████║██║░░██║░░░██║░░░██║██╔══╝░░░░╚██╔╝░░██║░░██║██╔══╝░░██╔══██╗██╔══██║██║██║░░██║
#██║░░░░░██║░╚═╝░██║██║░╚███║╚█████╔╝░░░██║░░░██║██║░░░░░░░░██║░░░╚█████╔╝██║░░░░░██║░░██║██║░░██║██║██████╔╝
#╚═╝░░░░░╚═╝░░░░░╚═╝╚═╝░░╚══╝░╚════╝░░░░╚═╝░░░╚═╝╚═╝░░░░░░░░╚═╝░░░░╚════╝░╚═╝░░░░░╚═╝░░╚═╝╚═╝░░╚═╝╚═╝╚═════╝░
# Связь с разработчиком:
# VK - @feymer31
# TG - @feymerwtf
settings:
  message-in-game-of-raid: true # Отправлять ли сообщение о рейде игроку в игре?
  message-in-telegram-of-raid: true # Отправлять ли сообщение о рейде игроку в телеграмм?
  message-in-vk-of-raid: true # Отправлять ли сообщение о рейде игроку в вк?
vk:
  settings:
    enable: true
    groupId: 111111111 # Айди группы вк
    accessToken: "token" # Токен группы вк
  messages:
    already-tied-up: "Вы уже привязали систему анти-рейда!" # Сообщение, когда игрок пытается привязать аккаунт к анти-рейд системе, но он уже привязан
    vk-tied-up: "На ваш игровой аккаунт было отправлено сообщение с кодом. Пожалуйста, напишите его комадой !анти-рейд код (код)" # Сообщение, когда игрок ввел команду !анти-рейд привязать (ник)
    player-null: "Игрок не найден!" # Сообщение, когда игрок не найден
    success-tied-up: "Вы успешно привязали анти-рейд систему! Теперь, когда ваш регион будут рейдить, вам будет приходить уведомление!" # Сообщение, когда игрок успешно привязал анти-рейд систему
    wrong-code: "Вы ввели неверный код!" # Сообщение, когда игрок вводит неверный код
    request-not-found: "Вы не отправляли запросы на привязку анти-рейд системы!" # Сообщение, когда игрок вводит командй !анти-рейд код (код), но он не пытался привязывать аккаунт к анти-рейд системе
    command-not-found: "Команда не найдена!" # Сообщение, когда игрок вводит неверную команду
    help: # Помощь по командам в вк
      - "Помощь по командам анти-рейд системы:"
      - ""
      - "!анти-рейд привязать (ник) - привязать аккаунт к системе анти-рейда"
      - "!анти-рейд код (код) - ввести код, чтобы подтвердить, что аккаунт именно ваш"
    notify-of-raid-in-vk: # Сообщение игроку в вк о том, что его регион рейдят
      - "Внимание! Ваш регион рейдят!"
      - ""
      - "Название региона: %region%"
      - "Координаты региона: %x%, %y%, %z%"
telegram:
  settings:
    enable: true
    bot-username: "username_bot" # Username бота
    bot-token: "token" # Токен бота
  messages:
    already-tied-up: "Вы уже привязали систему анти-рейда!" # Сообщение, когда игрок пытается привязать аккаунт к анти-рейд системе, но он уже привязан
    telegram-tied-up: "На ваш игровой аккаунт было отправлено сообщение с кодом. Пожалуйста, напишите его комадой !анти-рейд код (код)" # Сообщение, когда игрок ввел команду !анти-рейд привязать (ник)
    player-null: "Игрок не найден!" # Сообщение, когда игрок не найден
    success-tied-up: "Вы успешно привязали анти-рейд систему! Теперь, когда ваш регион будут рейдить, вам будет приходить уведомление!" # Сообщение, когда игрок успешно привязал анти-рейд систему
    wrong-code: "Вы ввели неверный код!" # Сообщение, когда игрок вводит неверный код
    request-not-found: "Вы не отправляли запросы на привязку анти-рейд системы!" # Сообщение, когда игрок вводит командй !анти-рейд код (код), но он не пытался привязывать аккаунт к анти-рейд системе
    command-not-found: "Команда не найдена!" # Сообщение, когда игрок вводит неверную команду
    help: # Помощь по командам в телеграмме
      - "Помощь по командам анти-рейд системы:"
      - ""
      - "!анти-рейд привязать (ник) - привязать аккаунт к системе анти-рейда"
      - "!анти-рейд код (код) - ввести код, чтобы подтвердить, что аккаунт именно ваш"
    notify-of-raid-in-telegram: # Сообщение игроку в телеграмм о том, что его регион рейдят
      - "Внимание! Ваш регион рейдят!"
      - ""
      - "Название региона: %region%"
      - "Координаты региона: %x%, %y%, %z%"
messages:
  notify-of-raid-in-game: # Сообщение игроку в игре о том, что его регион рейдят
    - "&fВнимание! Ваш регион &4рейдят&f!"
    - ""
    - "&fНазвание региона: &6%region%"
    - "&fКоординаты региона: &a%x%&f, &a%y%&f, &a%z%"
  game-tied-up: "&fПожалуйста, введите код в Телеграмм / ВК командой &6!анти-рейд код &6%code%&f, чтобы привязать анти-рейд систему!" # Сообщение игроку в игре, когда он написал команду !анти-рейд привязать (ник) в телеграмме
  reload: "&fВы перезагрузили плагин!" # Сообщение, когда плагин успешно перезагружен
  no-permission: "&fУ Вас недостаточно прав!" # Сообщение, когда у игрока не хватает прав
  no-args: "&fНедостаточно аргументов!" # Сообщение, когда при вводе команды не хватает агументов