#███████╗███╗░░░███╗███╗░░██╗░█████╗░████████╗██╗███████╗██╗░░░██╗░█████╗░███████╗██████╗░░█████╗░██╗██████╗░
#██╔════╝████╗░████║████╗░██║██╔══██╗╚══██╔══╝██║██╔════╝╚██╗░██╔╝██╔══██╗██╔════╝██╔══██╗██╔══██╗██║██╔══██╗
#█████╗░░██╔████╔██║██╔██╗██║██║░░██║░░░██║░░░██║█████╗░░░╚████╔╝░██║░░██║█████╗░░██████╔╝███████║██║██║░░██║
#██╔══╝░░██║╚██╔╝██║██║╚████║██║░░██║░░░██║░░░██║██╔══╝░░░░╚██╔╝░░██║░░██║██╔══╝░░██╔══██╗██╔══██║██║██║░░██║
#██║░░░░░██║░╚═╝░██║██║░╚███║╚█████╔╝░░░██║░░░██║██║░░░░░░░░██║░░░╚█████╔╝██║░░░░░██║░░██║██║░░██║██║██████╔╝
#╚═╝░░░░░╚═╝░░░░░╚═╝╚═╝░░╚══╝░╚════╝░░░░╚═╝░░░╚═╝╚═╝░░░░░░░░╚═╝░░░░╚════╝░╚═╝░░░░░╚═╝░░╚═╝╚═╝░░╚═╝╚═╝╚═════╝░
# Связь с разработчиком:
# VK - @feymer31
# TG - @feymerwtf
settings:
  message-in-game-of-raid: true # Отправлять ли сообщение о рейде игроку в игре?
  message-in-telegram-of-raid: true # Отправлять ли сообщение о рейде игроку в телеграмм?
telegram:
  settings:
    bot-username: "username_bot" # Username бота
    bot-token: "token" # Токен бота
  messages:
    already-tied-up: "Вы уже привязали систему анти-рейда!" # Сообщение, когда игрок пытается привязать аккаунт к анти-рейд системе, но он уже привязан
    telegram-tied-up: "На ваш игровой аккаунт было отправлено сообщение с кодом. Пожалуйста, напишите его комадой !анти-рейд код (код)" # Сообщение, когда игрок ввел команду !анти-рейд привязать (ник)
    player-null: "Игрок не найден!" # Сообщение, когда игрок не найден
    success-tied-up: "Вы успешно привязали анти-рейд систему! Теперь, когда ваш регион будут рейдить, вам будет приходить уведомление!" # Сообщение, когда игрок успешно привязал анти-рейд систему
    wrong-code: "Вы ввели неверный код!" # Сообщение, когда игрок вводит неверный код
    request-not-found: "Вы не отправляли запросы на привязку анти-рейд системы!" # Сообщение, когда игрок вводит командй !анти-рейд код (код), но он не пытался привязывать аккаунт к анти-рейд системе
    command-not-found: "Команда не найдена!" # Сообщение, когда игрок вводит неверную команду
    help: "Чтобы привязать аккаунт, используйте !анти-рейд привязать (ник), а чтобы ввести код - !анти-рейд код (код)"
messages:
  notify-of-raid-in-game: "&cВнимание! &fВаш регион &4%region% &fрейдят!" # Сообщение игроку в игре о том, что его регион рейдят
  notify-of-raid-in-telegram: "Внимание! Ваш регион %region% рейдят!" # Сообщение игроку в телеграмм о том, что его регион рейдят
  game-tied-up: "&fПожалуйста, введите код в Телеграмм командой &6!анти-рейд код &6%code%&f, чтобы привязать анти-рейд систему!" # Сообщение игроку в игре, когда он написал команду !анти-рейд привязать (ник) в телеграмме
  reload: "&fВы перезагрузили плагин!" # Сообщение, когда плагин успешно перезагружен
  no-permission: "&fУ Вас недостаточно прав!" # Сообщение, когда у игрока не хватает прав
  no-args: "&fНедостаточно аргументов!" # Сообщение, когда при вводе команды не хватает агументов